// Constants for playground
export const addresses = [
  { value: "all", label: "All addresses" },
  { value: "hn", label: "Ha Noi" },
  { value: "hcm", label: "Ho Chi Minh" },
  { value: "dn", label: "Da Nang" },
];

export const attractions = [
  { value: "water", label: "ウォーター" },
  { value: "botanical_garden", label: "植物園" },
  { value: "park", label: "公園" },
  { value: "shopping", label: "ショッピング" },
  { value: "restaurant", label: "レストラン" },
  { value: "climbing", label: "クライミング" },
  { value: "boat", label: "ボート" },
  { value: "bungee", label: "バンジー" },
  { value: "mini_golf", label: "ミニゴルフ" },
  { value: "kids_zone", label: "キッズゾーン" },
  { value: "history_books", label: "紀史書" },
  { value: "skydiving", label: "スカイダイビング" },
  { value: "amusement_park", label: "遊園地" },
  { value: "zoo", label: "動物園" },
  { value: "aquarium", label: "水族館" },
  { value: "museum", label: "博物館" },
  { value: "art_gallery", label: "美術館" },
  { value: "theater", label: "劇場" },
  { value: "concert_hall", label: "コンサートホール" },
  { value: "sports_center", label: "スポーツセンター" },
  { value: "skating_rink", label: "スケートリンク" },
  { value: "bowling", label: "ボウリング" },
  { value: "karaoke", label: "カラオケ" },
  { value: "cinema", label: "映画館" },
  { value: "game_center", label: "ゲームセンター" },
  { value: "escape_room", label: "脱出ゲーム" },
  { value: "spa", label: "スパ" },
  { value: "hot_spring", label: "温泉" },
  { value: "beach", label: "ビーチ" },
  { value: "mountain", label: "山" },
  { value: "camping", label: "キャンプ" },
  { value: "fishing", label: "釣り" },
  { value: "cycling", label: "サイクリング" },
  { value: "hiking", label: "ハイキング" },
  { value: "flower_garden", label: "フラワーガーデン" },
  { value: "theme_park", label: "テーマパーク" },
];

export const openTime = [
  { value: 0, label: "00:00" },
  { value: 6 * 3600, label: "06:00" },
  { value: 7 * 3600, label: "07:00" },
  { value: 7.5 * 3600, label: "07:30" },
  { value: 8 * 3600, label: "08:00" },
  { value: 8.5 * 3600, label: "08:30" },
  { value: 9 * 3600, label: "09:00" },
  { value: 9.5 * 3600, label: "09:30" },
];

export const closeTime = [
  { value: 24 * 3600, label: "23:59" },
  { value: 23.5 * 3600, label: "23:30" },
  { value: 23 * 3600, label: "23:00" },
  { value: 22.5 * 3600, label: "22:30" },
  { value: 22 * 3600, label: "22:00" },
  { value: 21.5 * 3600, label: "21:30" },
  { value: 21 * 3600, label: "21:00" },
  { value: 20.5 * 3600, label: "20:30" },
];
